## From raw csv to clean table

In [ ]:
import pandas as pd
df_raw_HDI = pd.read_csv('/content/Human Development Index - Full.csv')
df_raw_HDI.columns

Index(['ISO3', 'Country', 'Human Development Groups',
       'UNDP Developing Regions', 'HDI Rank (2021)',
       'Human Development Index (1990)', 'Human Development Index (1991)',
       'Human Development Index (1992)', 'Human Development Index (1993)',
       'Human Development Index (1994)',
       ...
       'Material footprint per capita (tonnes) (2012)',
       'Material footprint per capita (tonnes) (2013)',
       'Material footprint per capita (tonnes) (2014)',
       'Material footprint per capita (tonnes) (2015)',
       'Material footprint per capita (tonnes) (2016)',
       'Material footprint per capita (tonnes) (2017)',
       'Material footprint per capita (tonnes) (2018)',
       'Material footprint per capita (tonnes) (2019)',
       'Material footprint per capita (tonnes) (2020)',
       'Material footprint per capita (tonnes) (2021)'],
      dtype='object', length=880)

In [ ]:
#keep only certain columns to create a lighter dataframe
df_HDI = df_raw_HDI[["ISO3","Country","HDI Rank (2021)","Human Development Index (1990)","Human Development Index (2005)","Human Development Index (2021)"]]
df_HDI

,ISO3,Country,HDI Rank (2021),Human Development Index (1990),Human Development Index (2005),Human Development Index (2021)
0,AFG,Afghanistan,180.0,0.273,0.400,0.478
1,AGO,Angola,148.0,NaN,0.447,0.586
2,ALB,Albania,67.0,0.647,0.711,0.796
3,AND,Andorra,40.0,NaN,0.833,0.858
4,ARE,United Arab Emirates,26.0,0.728,0.822,0.911
...,...,...,...,...,...,...
190,WSM,Samoa,111.0,NaN,0.701,0.707
191,YEM,Yemen,183.0,0.383,0.489,0.455
192,ZAF,South Africa,109.0,0.632,0.632,0.713
193,ZMB,Zambia,154.0,0.412,0.472,0.565
194,ZWE,Zimbabwe,146.0,0.509,0.448,0.593

In [ ]:
#formating data types
df_HDI.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ISO3                            195 non-null    object
 1   Country                         195 non-null    object
 2   HDI Rank (2021)                 191 non-null    float64
 3   Human Development Index (1990)  141 non-null    float64
 4   Human Development Index (2005)  186 non-null    float64
 5   Human Development Index (2021)  191 non-null    float64
dtypes: float64(4), object(2)
memory usage: 9.3+ KB

In [ ]:
#dropping row with Nan values in "HDI Rank (2021)"
df_HDI = df_HDI[~ df_HDI["HDI Rank (2021)"].isna()]

In [ ]:
df_HDI["HDI_Rank"] = df_HDI["HDI Rank (2021)"].map(lambda x : int(x)) #formatting HDI RANK 2021 as int64 and storing the result in a new column HDI_Rank

In [ ]:
df_HDI.info()
df_HDI.drop(["HDI Rank (2021)","HDI"],axis = 1, inplace = True) #dropping useless columns
df_HDI

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191 entries, 0 to 194
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ISO3                            191 non-null    object
 1   Country                         191 non-null    object
 2   HDI Rank (2021)                 191 non-null    float64
 3   Human Development Index (1990)  141 non-null    float64
 4   Human Development Index (2005)  186 non-null    float64
 5   Human Development Index (2021)  191 non-null    float64
 6   HDI                             191 non-null    int64
 7   HDI_Rank                        191 non-null    int64
dtypes: float64(4), int64(2), object(2)
memory usage: 13.4+ KB

,ISO3,Country,Human Development Index (1990),Human Development Index (2005),Human Development Index (2021),HDI_Rank
0,AFG,Afghanistan,0.273,0.400,0.478,180
1,AGO,Angola,NaN,0.447,0.586,148
2,ALB,Albania,0.647,0.711,0.796,67
3,AND,Andorra,NaN,0.833,0.858,40
4,ARE,United Arab Emirates,0.728,0.822,0.911,26
...,...,...,...,...,...,...
190,WSM,Samoa,NaN,0.701,0.707,111
191,YEM,Yemen,0.383,0.489,0.455,183
192,ZAF,South Africa,0.632,0.632,0.713,109
193,ZMB,Zambia,0.412,0.472,0.565,154
194,ZWE,Zimbabwe,0.509,0.448,0.593,146

In [ ]:
#filling NaN values in "Human Development Index (1990)" & "Human Development Index ()"
df_HDI['Human Development Index (1990)'] = df_HDI['Human Development Index (1990)'].interpolate(method='linear', limit_direction='both', limit_area='inside')
df_HDI['Human Development Index (2005)'] = df_HDI['Human Development Index (2005)'].interpolate(method='linear', limit_direction='both', limit_area='inside')
df_HDI

,ISO3,Country,Human Development Index (1990),Human Development Index (2005),Human Development Index (2021),HDI_Rank
0,AFG,Afghanistan,0.2730,0.400,0.478,180
1,AGO,Angola,0.4600,0.447,0.586,148
2,ALB,Albania,0.6470,0.711,0.796,67
3,AND,Andorra,0.6875,0.833,0.858,40
4,ARE,United Arab Emirates,0.7280,0.822,0.911,26
...,...,...,...,...,...,...
190,WSM,Samoa,0.4160,0.701,0.707,111
191,YEM,Yemen,0.3830,0.489,0.455,183
192,ZAF,South Africa,0.6320,0.632,0.713,109
193,ZMB,Zambia,0.4120,0.472,0.565,154
194,ZWE,Zimbabwe,0.5090,0.448,0.593,146

In [ ]:
#scouting for abnormal or extreme values
df_HDI.describe()

,Human Development Index (1990),Human Development Index (2005),Human Development Index (2021),HDI_Rank
count,191.000000,191.000000,191.000000,191.000000
mean,0.598688,0.663877,0.720576,95.811518
std,0.153392,0.161831,0.150661,55.307333
min,0.216000,0.298000,0.385000,1.000000
25%,0.484500,0.525000,0.599500,48.500000
50%,0.626000,0.695000,0.739000,96.000000
75%,0.717000,0.796500,0.835000,143.500000
max,0.872000,0.931000,0.962000,191.000000

In [ ]:
#saving df to a csv to load it to BigQuery
df_HDI.to_csv("HDI.csv", index=False)